name: Deploy new-ui to Vercel
on:
  push: { branches: [ new-ui ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      # секреты уже есть в репозитории
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID_NEW }}
    steps:
      - uses: actions/checkout@v4
      - name: Whoami (debug)
        run: |
          npx -y vercel@latest --version
          npx -y vercel@latest whoami --token "$VERCEL_TOKEN" || true
          env | grep ^VERCEL_ || true
      - name: Remote deploy (prod)
        run: npx -y vercel@latest deploy --prod --yes --debug \
             --name adsrays-new-ui \
             --scope adsrays \
             --token "$VERCEL_TOKEN"
