name: Deploy legacy-ui to Vercel
on:
  push: { branches: [ legacy-ui-build ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Install deps
        run: npm ci || npm i --legacy-peer-deps --no-audit --no-fund

      - name: vercel link (by name)
        run: npx -y vercel@latest link \
               --project adsrays-legacy-ui \
               --yes --scope adsrays \
               --token ${{ secrets.VERCEL_TOKEN }}

      - name: vercel pull (prod)
        run: npx -y vercel@latest pull --yes --environment=production \
               --token ${{ secrets.VERCEL_TOKEN }}

      - name: vercel build
        run: npx -y vercel@latest build --token ${{ secrets.VERCEL_TOKEN }}

      - name: vercel deploy (prebuilt, prod)
        run: npx -y vercel@latest deploy --prebuilt --prod \
               --token ${{ secrets.VERCEL_TOKEN }}
