name: Deploy new-ui to Vercel
on:
  push: { branches: [ new-ui ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Ensure jq
        run: sudo apt-get update -y && sudo apt-get install -y jq

      - name: Show project.json
        run: |
          test -s .vercel/project.json || (echo "No .vercel/project.json" && exit 1)
          cat .vercel/project.json

      - name: Export IDs from project.json
        run: |
          echo "VERCEL_ORG_ID=$(jq -r '.orgId' .vercel/project.json)" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=$(jq -r '.projectId' .vercel/project.json)" >> $GITHUB_ENV

      - name: Install deps
        run: npm ci || npm i --legacy-peer-deps --no-audit --no-fund

      - name: vercel pull (prod)
        run: npx -y vercel@latest pull --yes --environment=production --debug --token "$VERCEL_TOKEN"

      - name: vercel build
        run: npx -y vercel@latest build --token "$VERCEL_TOKEN"

      - name: vercel deploy (prebuilt)
        id: prebuilt
        continue-on-error: true
        run: |
          set -o pipefail
          npx -y vercel@latest deploy --prebuilt --prod --debug --token "$VERCEL_TOKEN" 2>&1 | tee deploy.log || true
          # вытаскиваем ЛЮБУЮ vercel.app ссылку
          URL="$(grep -Eo 'https://[^ ]+vercel\.app' deploy.log | tail -1 || true)"
          echo "URL=$URL" >> "$GITHUB_OUTPUT"

      - name: Fallback deploy (remote build)
        id: fallback
        if: steps.prebuilt.outcome == 'failure'
        run: |
          set -o pipefail
          npx -y vercel@latest deploy --prod --yes --debug --token "$VERCEL_TOKEN" 2>&1 | tee deploy_fallback.log || true
          URL="$(grep -Eo 'https://[^ ]+vercel\.app' deploy_fallback.log | tail -1 || true)"
          echo "URL=$URL" >> "$GITHUB_OUTPUT"

      - name: Publish Production URL
        if: always()
        env:
          PRE: ${{ steps.prebuilt.outputs.URL }}
          FALL: ${{ steps.fallback.outputs.URL }}
        run: |
          URL="$PRE"; [ -z "$URL" ] && URL="$FALL"
          if [ -n "$URL" ]; then
            echo "Production: $URL" | tee -a "$GITHUB_STEP_SUMMARY"
            echo "$URL"
          else
            echo "No Production URL found" >&2
            echo '--- prebuilt tail ---'; tail -n 80 deploy.log || true
            echo '--- fallback tail ---'; tail -n 80 deploy_fallback.log || true
            exit 1
          fi
