name: Deploy new-ui to Vercel
on:
  push: { branches: [ new-ui ] }
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Remote deploy (prod)
        run: npx -y vercel@latest deploy --prod --yes \
             --project ${{ secrets.VERCEL_PROJECT_ID_NEW }} \
             --scope adsrays \
             --token $VERCEL_TOKEN
