name: Deploy new-ui to Vercel
on:
  push: { branches: [ new-ui ] }
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }

      - name: Show project.json
        run: |
          test -s .vercel/project.json || (echo "No .vercel/project.json"; exit 1)
          cat .vercel/project.json

      - name: Export IDs from project.json
        run: |
          echo "VERCEL_ORG_ID=$(jq -r '.orgId' .vercel/project.json)" >> $GITHUB_ENV
          echo "VERCEL_PROJECT_ID=$(jq -r '.projectId' .vercel/project.json)" >> $GITHUB_ENV

      - name: vercel whoami (debug)
        run: npx -y vercel@latest whoami --token "$VERCEL_TOKEN" || true

      # ЧИСТЫЙ remote deploy (без pull и без локального build)
      - name: vercel deploy (remote, prod)
        run: |
          npx -y vercel@latest deploy --prod --yes \
            --project "$VERCEL_PROJECT_ID" \
            --scope adsrays \
            --token "$VERCEL_TOKEN" \
          | tee deploy.log
          echo "-----"
          echo "Production URL:"
          sed -nE 's/.*(Production|Alias): *\(? *(https[^ )]+).*/\2/p' deploy.log | tail -1
