name: Deploy new-ui to Vercel
on:
  push:
    branches: [ new-ui ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Remote deploy to Vercel (prod)
        run: npx -y vercel@latest deploy --prod --yes --name adsrays-new-ui --scope adsrays --token ${{ secrets.VERCEL_TOKEN }}
